#!/usr/bin/python3

//second merge conflict
//pi2 test
def main(msg):
    print(msg)

main("Hello git")
